### ISSUE TITLE
Improve `Vector2` and `Color` implementations

### ISSUE THREAD

**Issue by michabay05** [RSC-Games/Velocity-CPP#6]
Currently, these structures are lacking as they only contain their attributes and constructors.

To fully implement this feature, the following must be included.
- [x] `Vector2` Operations
    - [x] 4 Arithmetic Operators (add, subtract, multiply, and divide)
    - [x] Scaling by a factor
    - [x] Dot product
    - [x] Length and squared length
    - [x] Linear interpolation
    - [x] Distance between two vectors
    - [x] Equality Comparison

- [x] `Vector2` Constants
    - Zero, One, Up, Down, Left, Right

- [x] `Color` Operations
    - [x] From hex value (`0xFF000000` maps to red)
    - [x] Increase or decrease Opacity (Alpha)

- [x] `Color` Constants
    - Red, Green, Blue, Yellow, Magenta, Cyan, Orange

**Comment by RSC-Games** [comment]
Alternatively we could also use GLM if that helps.

**Comment by michabay05** [comment]
This is the user-facing utility implementation. The OpenGL renderer will internally use `glm`; however, given `glm`'s large nature, requiring the user to use it didn't sound appealing. So, these implementations are meant to be simpler, yet feature-full implementations that the user can use to create games.

**Comment by RSC-Games** [comment]
Alright that makes sense.
