### ISSUE TITLE
Name the RSC Games-maintained renderer suite NativeViper

### ISSUE THREAD

**Issue by RSC-Games** [RSC-Games/Velocity-CPP#9]
The Java-based Velocity has multiple renderers. The basic ERP, which does extremely basic drawing, and the LumaViper suite of renderers (LVCPU, LVDX11, LVOGL).

I propose renaming the C++ renderers NVCPU, NVOGL, and NVDX12, to avoid confusion with the Java-based Velocity.

**Comment by michabay05** [comment]
The renderer has been renamed and integrated into the main branch.

**Comment by michabay05** [comment]
Commit e3c26c7
